/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.docklokman.dimnamegen;

import com.formdev.flatlaf.FlatDarkLaf;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DocKlokMan
 */
public class DimNameGen extends javax.swing.JFrame {

    /**
     * Creates new form DimNameGen
     */
    public DimNameGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        LblInstructions = new javax.swing.JLabel();
        NameInputScroll = new javax.swing.JScrollPane();
        NameInput = new javax.swing.JTextArea();
        BtnGenerate = new javax.swing.JButton();
        CbKeepOrder = new javax.swing.JCheckBox();
        LblOutputFolder = new javax.swing.JLabel();
        txtOutputFolderName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DIM Name Generator");
        setResizable(false);
        setLocationRelativeTo(null);

        LblInstructions.setText("Enter a name or list of names (one per line) to generate");
        LblInstructions.setToolTipText("");

        NameInput.setColumns(10);
        NameInput.setRows(5);
        NameInputScroll.setViewportView(NameInput);

        BtnGenerate.setText("Generate");
        BtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateActionPerformed(evt);
            }
        });

        CbKeepOrder.setText("Keep Order");
        CbKeepOrder.setToolTipText("Appends a number before the generated file "
                + "name to ensure the files are sorted in the order they were "
                + "generated");

        LblOutputFolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblOutputFolder.setText("Output Folder Name");
        LblOutputFolder.setToolTipText("");

        txtOutputFolderName.setMaximumSize(new java.awt.Dimension(131, 32));
        txtOutputFolderName.setMinimumSize(new java.awt.Dimension(131, 32));
        txtOutputFolderName.setPreferredSize(new java.awt.Dimension(131, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblInstructions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameInputScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(BtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbKeepOrder)
                            .addComponent(LblOutputFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOutputFolderName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameInputScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(BtnGenerate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbKeepOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(LblOutputFolder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtOutputFolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void BtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {                                            
        try {
            new GenerateSprites().generateSprites(NameInput.getText(), txtOutputFolderName.getText(), CbKeepOrder.isSelected());
        } catch (IOException ex) {
            Logger.getLogger(DimNameGen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        FlatDarkLaf.setup();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DimNameGen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BtnGenerate;
    private javax.swing.JCheckBox CbKeepOrder;
    private javax.swing.JLabel LblInstructions;
    private javax.swing.JLabel LblOutputFolder;
    private javax.swing.JTextArea NameInput;
    private javax.swing.JScrollPane NameInputScroll;
    private javax.swing.JTextField txtOutputFolderName;
}
